### ISSUE TITLE
Setup Google Login

### ISSUE THREAD

**Issue by kanishq1** [Devsoc-BPGC/Short-Me#21]
**Is your feature request related to a problem? Please describe.**
Everyone likes multiple option to login but direct google login is most preffered

**Describe the solution you'd like**
Setup Google-login in the react app.

**Describe alternatives you've considered**

**Additional context**

**Comment by Aviral09** [comment]
I can setup google login but I need credentials generated from the google developer account which you want to link with the project for the same.

**Comment by kanishq1** [comment]
For now you can start with your credentials once that's complete we'll provide you the devsoc creds.

**Comment by Manthan-Asher** [comment]
We can also add Facebook/LinkedIn/twitter login along with google

**Comment by Manthan-Asher** [comment]
has this feature been added by someone?

**Comment by kanishq1** [comment]
Not yet

**Comment by Aviral09** [comment]
Added this feature to react app.
